plugins {
	id 'java'
	id 'jacoco'
	id 'info.solidsoft.pitest' version '1.19.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}


repositories {
	mavenCentral()
}

test {
	useJUnitPlatform()
}

pitest {
	targetClasses = ['ch.bbw.m450.tictactoe.*']
	targetTests = ['ch.bbw.m450.tictactoe.*']
	junit5PluginVersion = '1.2.1'
	outputFormats = ['HTML', 'XML']
	timestampedReports = false
}

jacocoTestReport {
	reports {
		xml.required = true
		html.required = true
	}
}

dependencies {
testImplementation 'org.assertj:assertj-core:3.27.7'
testImplementation 'org.junit.jupiter:junit-jupiter:6.1.3'
testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
