name: Gradle CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/flycaptainrex/tictactest-devcontainer:stable

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v6

      - name: Java einrichten
        run: java --version

      - name: Gradle einrichten
        uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: ./gradlew assemble --no-daemon

      - name: Test und Coverage
        run: ./gradlew test jacocoTestReport --no-daemon
